
const ADD_PHOTOS = 'ADD_PHOTOS';
const ADD_TO_BLACK_LIST ='ADD_TO_BLACK_LIST';
const REMOVE_FROM_BLACK_LIST ='REMOVE_FROM_BLACK_LIST';

export {
    ADD_PHOTOS,
    ADD_TO_BLACK_LIST,
    REMOVE_FROM_BLACK_LIST,
}