const SET_PRODUCTS = 'SET_PRODUCTS';
const START_PRODUCTS_LOADING = 'START_PRODUCTS_LOADING';
const END_PRODUCTS_LOADING = 'END_PRODUCTS_LOADING';

export {
    SET_PRODUCTS,
    START_PRODUCTS_LOADING,
    END_PRODUCTS_LOADING,
}